---
functional:
  - требование 3
  - требование 4
  - требование 8
  - требование 9
non-functional:
  - требование 1
  - требование 2
  - требование 5
  - требование 6
  - требование 7
  - требование 10
implicit: 
  - требование 11 Наличие сертификата соответствия Гост Р
  - требование 12 Сертификат соответствия на средства связи, ССС
  - требование 13 Соответствие тр ТС "О безопасности пищевой продукции» 021/2011"
  - требование 14 Соответствие тр ТС "О безопасности парфюмерно-косметической продукции"(ТР ТС 009/2011)
  - требование 15 Сертификат экологической безопасности Евро 4
